name: Build and Deploy to Sandbox

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout this repo
              uses: actions/checkout@v2
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                path: ~/.m2/re[ository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  ${{ runner.os }}-maven-
            - name: Set up JDK 1.8
              uses: actions/setup-java@v3
              with:
                java-version: 8
                distribution: 'zulu'
            - name: Build with Maven
              run: mvn -B package --file pom.xml
            - name: Stamp artifact file name with commit hash
              run: |
                artifactName1=$(ls target/*.jar | head -n 1)
                commitHash=$(git rev-parse --short "$GITHUB_SHA")
                artifactName2=$(ls target/*.jar | head -n 1 | sed "s/.jar/-${commitHash}.jar/g")
                mv $artifactName1 $artifactName2
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: artifacts
                path: target/*.jar
